CREATE TABLE PESSOA
(ID INT IDENTITY(1,1) PRIMARY KEY,
NM_NOME VARCHAR(255),
NM_SOBRENOME VARCHAR(255),
DT_NASCIMENTO DATETIME
);


CREATE TABLE PRODUTO
(ID INT IDENTITY(1,1) PRIMARY KEY,
NM_NOME VARCHAR(255),
NR_PRECO VARCHAR(255),
NR_QUANTIDADE INT
);

