CREATE TABLE PESSOA
(ID INT IDENTITY(1,1) PRIMARY KEY,
NM_NOME VARCHAR(255),
NM_SOBRENOME VARCHAR(255),
DT_NASCIMENTO DATETIME
);




CREATE TABLE [dbo].[PRODUTO] (
    [ID]         INT          IDENTITY (1, 1) NOT NULL,
    [NM_NOME]       NCHAR (255)  NOT NULL,
    [NR_PRECO]      VARCHAR (255) NOT NULL,
    [NR_QUANTIDADE] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);